---
title: "harpreet-other-2"
author: "Harpreet Kaur"
date: "14/02/2022"
output: html_document
---


```{r}
# libraries imported
library(httr)
library(jsonlite)
library(dplyr)
library(lubridate)
library(testthat)
```



```{r}

request_fun <- function(){
 #' @title Make Request to API url for content extraction
  #'
  #' @description The function will pass a get request to the url mentioned in the function and help in accessing the json/xml/html content of the web page. If the returned response code is 200 that means everything is good.
  #' @param is none
  #'
  #' @returns the response
  #' @example url = 'https://api.opencovid.ca/summary?date=01-09-2020'
  #'
  url <- 'https://api.opencovid.ca/other?stat=prov'
  request <- GET(url)
  return(request)
}

```

```{r}
province_population <- function(provinceName = 'Canada'){
  #' @title Total population segregated for every Canadian province.
  #'
  #' @description The total population count for every province is individual mentioned.
  #' It processes the API and returns the json data corresponding to entered province. exceptional user input have been handled. If 'Canada' is passed as an argument the output displays the data for all the Canadian provinces.The returned data is a data frame and,
  #'
  #' @param provinceName (not abbreviated)
  #'
  #' @return Data frame with all the columns for the entire summary for all the provinces individually would be returned. The columns includes the date, province name, active_cases, active_cases_change, avaccine, cases,cumulative_avaccine, cumulative_cases,cumulative_cvaccine, cumulative_deaths,   cumulative_dvaccine, cumulative_recovered, cumulative_testing, cvaccine, deaths, dvaccine, recovered, testing and testing_info.
  #'
  #' @examples province_population("Ontario")
  prov = c("Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Nunavut", "Northwest Territories", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon", "Canada")
  
  `%!in%` <- Negate(`%in%`) 
  if(tolower(provinceName) %!in% tolower(prov)){
    stop("Please enter a valid province name in full form!")
  }
  
  request <- request_fun()
  json_data <- content(request, as  = "parse")
  all_active <- json_data$active
  active_data <- data.frame()
  
  
  for(i in 1:length(json_data[[1]])){

    active_data <- rbind(active_data, data.frame(json_data[[1]][[i]]))
  }
  
  
  active_data <- active_data %>%
    mutate(province = replace(province, province %in% c("BC"), "British Columbia"),
           province = replace(province, province %in% c("NL"), "Newfoundland and Labrador"),
           province = replace(province, province %in% c("NWT"), "Northwest Territories"),
           province = replace(province, province %in% c("PEI"), "Prince Edward Island"))
  
  
  active_data <- active_data[,c(2,1)]
  print(active_data)
  if(tolower(provinceName) == "canada"){
    return(active_data)
  } else {
    active_data <- active_data %>%
      filter(tolower(province) == tolower(provinceName))
    return(active_data)
  }
  
}


data <- province_population('ALBERTA')
```

```{r}
# Test cases

test_that("testing of summary_of_peaktime", {
  expected <- province_population("Ontario")
  expect_that(expected, is_a("data.frame"))
  expect_equal(unique(expected$province), "Ontario")
  expect_that(length(expected), equals(2))
  expect_error(province_population("BC"), "Please enter a valid province name in full form!")
})
```