---
title: "Harpreet-summary-3"
author: "Harpreet Kaur"
date: "13/02/2022"
output: html_document
---

```{r}
# libraries imported
library(httr)
library(jsonlite)
library(dplyr)
library(lubridate)
library(testthat)
```

```{r}

request_fun <- function(){
  #' @title Make Request to API url for content extraction
  #'
  #' @description The function will pass a get request to the url mentioned in the function and help in accessing the json/xml/html content of the web page. If the returned response code is 200 that means everything is good.
  #' @param is none
  #'
  #' @returns the response
  #' @example url = 'https://api.opencovid.ca/summary?date=01-09-2020'
  #'
  url <- 'https://api.opencovid.ca/summary?loc=canada&date=01-09-2020'
  request <- GET(url)
  return(request)
}

```

```{r}
summary_of_canada <- function(provinceName = "Canada") {

  #' @title Covid-19 peak time which is September 2020 summary for entire Canada
  #'
  #' @description Summary for the entire country relating to Covid-19 peak time in Canada which is the month of September 2020 : the active cases, avaccine, cvaccine and dvaccine. Moreover, is discloses the count of people who have recovered and who were tested on September 01, 2020.
  #' It processes the API and returns the json data corresponding to the summary from all the data for all the Canadian provinces.The returned data is a data frame and,
  #'
  #' @param none passed default
  #'
  #' @return Data frame with all the columns for the entire summary for all the provinces individually would be returned. The columns includes the date, province name, active_cases, active_cases_change, avaccine, cases,cumulative_avaccine, cumulative_cases,cumulative_cvaccine, cumulative_deaths,   cumulative_dvaccine, cumulative_recovered, cumulative_testing, cvaccine, deaths, dvaccine, recovered, testing and testing_info.
  #'
  #' @examples summary_of_canada("Ontario")
  
  request <- request_fun()
  json_data <- content(request, as  = "parse")
  all_active <- json_data$active
  active_data <- data.frame()
  
  #print(json_data[[1]])
  for(i in 1:length(json_data[[1]])){

    active_data <- rbind(active_data, data.frame(json_data[[1]][[i]]))
  }
  
  
  active_data <- active_data %>%
    mutate(date, date = dmy(date)) 
  
  
  active_data <- active_data[,c(13,16,1:12,14:15,17:19)]
  
}


data <- summary_of_canada('CANADA')
```

```{r}
# Test cases

test_that("testing of summary_of_canada", {
  expected <- summary_of_canada("Canada")
  expect_that(expected, is_a("data.frame"))
  expect_that(length(expected), equals(19))
  expect_error(active_cases("CA"), "Please enter a valid country name in full form!")
})
```