---
title: "API - Summary"
author: "Harpreet Kaur"
date: "12/02/2022"
output: html_document
---

```{r}
# libraries imported
library(httr)
library(jsonlite)
library(dplyr)
library(lubridate)
library(testthat)
```


```{r}

request_fun <- function() {
  #' @title Make Request to API url for content extraction
  #'
  #' @description The function will pass a get request to the url mentioned in the function and help in accessing the json/xml/html content of the web page. If the returned response code is 200 that means everything is good.
  #' @param is none
  #'
  #' @returns the response
  #' @example url = 'https://api.opencovid.ca/summary'
  #'
  url <- "https://api.opencovid.ca/summary"
  request <- GET(url)
  return(request)
}
```

```{r}
summary_of_cases <- function(provinceName = "Canada") {

  #' @title Covid-19 particular day\'s individual summary for every Canadian province
  #'
  #' @description Summary for all the provinces relating to Covid-19 active cases, avaccine, cvaccine and dvaccine. Moreover, is discloses the count of people who have recovered and who were tested.
  #' It processes the API and returns the json data corresponding to entered province. exceptional user input have been handled. If 'Canada' is passed as an argument the output displays the data for all the Canadian provinces.The returned data is a data frame and,
  #'
  #' @param provinceName (not abbreviated)
  #'
  #' @return Data frame with all the columns for the entire summary for all the provinces individually would be returned. The columns includes the date, province name, active_cases, active_cases_change, avaccine, cases,cumulative_avaccine, cumulative_cases,cumulative_cvaccine, cumulative_deaths,   cumulative_dvaccine, cumulative_recovered, cumulative_testing, cvaccine, deaths, dvaccine, recovered, testing and testing_info.
  #'
  #' @examples summary_of_cases("Ontario")

  prov <- c("Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Nunavut", "Northwest Territories", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon", "Canada")

  `%!in%` <- Negate(`%in%`) # taking care of the cases of letter
  if (tolower(provinceName) %!in% tolower(prov)) {
    stop("Please enter a valid province name in full form!")
  }

  request <- request_fun() # request to url
  json_data <- content(request, as = "parse") # json for the url
  active_data <- data.frame() # empty frame for appending

  # data extraction
  for (i in 1:length(json_data[[1]])) {
    active_data <- rbind(active_data, data.frame(json_data[[1]][[i]]))
  }

  # dataframe wrangling
  active_data <- active_data %>%
    mutate(date, date = dmy(date)) %>%
    mutate(
      province = replace(province, province %in% c("BC"), "British Columbia"),
      province = replace(province, province %in% c("NL"), "Newfoundland and Labrador"),
      province = replace(province, province %in% c("NWT"), "Northwest Territories"),
      province = replace(province, province %in% c("PEI"), "Prince Edward Island")
    )


  active_data <- active_data[, c(13, 16, 1:12, 14:15, 17:19)] # extracted keys
  # sensitive case handling
  if (tolower(provinceName) == "canada") {
    return(active_data)
  } else {
    active_data <- active_data %>%
      filter(tolower(province) == tolower(provinceName))
    return(active_data)
  }
}


data <- summary_of_cases("ALBERTA")
```


```{r}
# Test cases

test_that("testing of summary_of_cases", {
  expected <- summary_of_cases("Alberta")
  expect_that(expected, is_a("data.frame"))
  expect_equal(unique(expected$province), "Alberta")
  expected <- summary_of_cases("Ontario")
  expect_that(length(expected), equals(19))
  expect_error(active_cases("BC"), "Please enter a valid province name in full form!")
})
```
