---
title: "demo_api"
author: "Jagdeep Brar"
date: "11/02/2022"
output: html_document
---

```{r}
library(httr)
library(jsonlite)
library(dplyr)
library(lubridate)
library(testthat)
```

```{r}

request_fun <- function(){
#' Function to make request to API and returns the response 
  url <- 'https://api.opencovid.ca/timeseries'
  request <- GET(url)
  return(request)
}

```

```{r}
active_cases <- function(provinceName = 'Canada'){
  #' @title  Returns a dataframe of active Covid-19 cases in desired province of Canada
  #'
  #' @description Perform data wrangling and cleaning using the API for the Covid-19 cases in Canada.
  #' It processes the API and returns the data corresponding to one province which is passed on as the argument. If user passes empty      #' argument, so by default Canada is used which returns the data of whole Canada as a  whole.
  #' The returned data is a data frame and contains the columns including the date, province name, active cases, change is active cases,
  #' cumulative cases, cumulative deaths and cumulative recovered.
  #'
  #' @param provinceName a character/string depicting the name of the province
  #'
  #' @return Data frame for the Covid-19 active cases  corresponding to a particular province
  #'
  #' @examples active_cases("Alberta")
  
  prov = c("Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Nunavut", "Northwest Territories", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon", "Canada")
  
  `%!in%` <- Negate(`%in%`) 
  if(tolower(provinceName) %!in% tolower(prov)){
    stop("Please enter a valid province name in full form!")
  }
  
  request <- request_fun()
  json_data <- content(request, as  = "parse")
  all_active <- json_data$active
  active_data <- data.frame()
  
  for(i in 1:length(all_active)){
    active_data <- rbind(active_data, data.frame(all_active[[i]]))
  }
  
  active_data <- active_data %>% rename(date = date_active) %>%
    mutate(date, date = dmy(date)) %>%
    mutate(province = replace(province, province %in% c("BC"), "British Columbia"),
           province = replace(province, province %in% c("NL"), "Newfoundland and Labrador"),
           province = replace(province, province %in% c("NWT"), "Northwest Territories"),
           province = replace(province, province %in% c("PEI"), "Prince Edward Island"))
  
  
  active_data <- active_data[,c(6,7,1:5)]
  
  if(tolower(provinceName) == "canada"){
    return(active_data)
  } else {
    active_data <- active_data %>%
      filter(tolower(province) == tolower(provinceName))
    return(active_data)
  }
}


data <- active_cases('ALBERTA')
```



```{r}
test_that("testing of active_cases", {
  expected <- active_cases("Alberta")
  expect_s3_class(expected, "data.frame")
  expect_equal(unique(expected$province), "Alberta")
  expect_error(active_cases("BC"), "Please enter a valid province name in full form!")
})
```

```{r}
Yearlycases_as_per_province <- function(provinceName = 'Canada',yearpassed='2020'){
  #' @title Function for returning data frame for the Covid - 19 cases in different provinces as per the year specified in Canada.
  #'
  #' @description Performed data wrangling and cleaning using the API for the Covid - 19 cases in Canada.
  #' It processes the API and returns the data corresponding to one province
  #' which is passed on as the argument. If user passes empty argument, so by default Canada is used which returns the data of whole Canada as a whole.
  #' Also, the data is returned as per the year. By default the year chosen is 2020.
  #' The returned data is a data frame and contains the columns including the date of the cases, province name, cases and cumulative cases for the year 	    #' specified
  #'
  #' @param provinceName a character/ string depicting the name of the province
  #' @param yearpassed a character/ string depicting the year
  #'
  #' @return Data frame for the Covid - 19 cases corresponding to a particular province and year
  #'
  #' @examples Yearlycases_as_per_province('Alberta','2020')

  prov = c("Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Nunavut", "Northwest Territories", "Ontario", "Prince Edward 	                Island", "Quebec", "Saskatchewan", "Yukon", "Canada")
  `%!in%` <- Negate(`%in%`)
  if(tolower(provinceName) %!in% tolower(prov)){
    stop("Please enter a valid province name that too in its full form!")
  }
  
  year_check <- gsub(" ", "", paste(yearpassed, "-01-01"))
  if(is.na(ymd(year_check))){
    stop("Please enter a valid year as string in format yyyy !!")
  }

  request <- request_fun()

  json_data <- content(request, as  = "parse")
  cases <- json_data$cases
  cases_data <- data.frame()
  for(i in 1:length(cases)){
    cases_data <- rbind(cases_data, data.frame(cases[[i]]))
  }

  cases_data <- cases_data %>%
    rename('date' = 'date_report') %>%
    mutate(date=as.Date(date, format = "%d-%m-%Y"))%>%
    mutate(province = replace(province, province %in% c("BC"), "British Columbia"),
           province = replace(province, province %in% c("NL"), "Newfoundland and Labrador"),
           province = replace(province, province %in% c("NWT"), "Northwest Territories"),
           province = replace(province, province %in% c("PEI"), "Prince Edward Island")) %>%
    mutate(year = format(date, format = "%Y"))

  cases_data <- cases_data[, c(3, 4, 1, 2, 5)]
  
  if(yearpassed %!in% unique(cases_data$year)){
    stop("There is no data for this year!")
  }

  if(tolower(provinceName) == 'canada'){
    cases_data <- cases_data %>%
      filter(year==yearpassed)
    return(cases_data)
  } else {
    cases_data <- cases_data %>%
      filter(tolower(province) == tolower(provinceName),year==yearpassed)
    return(cases_data)
  }
}

data <- Yearlycases_as_per_province(provinceName = 'Canada', yearpassed="2022")
```

```{r}
yearly_recovered<- function(provinceName = 'Canada', ryear='2020'){
  #' @title Function for returning data frame for the Covid - 19 recovered cases in different provinces in Canada according to the year.
  #'
  #' @description Performed data wrangling and cleaning using the API for the Covid - 19 cases in Canada.
  #' It processes the API and returns the data corresponding to one province
  #' which is passed on as the argument. If user passes empty argument, so by default Canada is used which returns the data of whole Canada as a whole.
  #' The returned data is a data frame and contains the columns including the recovery date, province, cumulative recovered, and count of recovery.
  #'
  #' @param provinceName a character/ string depicting the name of the province
  #' @param ryear a character/ string showing the year
  #'
  #' @return Data frame for the Covid - 19 recovery corresponding to a particular province and year
  #'
  #' @examples yearly_recovered('Alberta','2020')

  prov = c("Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Nunavut", "Northwest Territories", "Ontario", "Prince Edward 	                Island", "Quebec", "Saskatchewan", "Yukon", "Canada")
  `%!in%` <- Negate(`%in%`)
  if(tolower(provinceName) %!in% tolower(prov)){
    stop("Please enter a valid province name that too in its full form!")
  }

  year_check <- gsub(" ", "", paste(ryear, "-01-01"))
  if(is.na(ymd(year_check))){
    stop("Please enter a valid year as string in format yyyy !!")
  }
  request <- request_fun()

  json_data <- content(request, as  = "parse")
  recovered <- json_data$recovered
  recovered_data <- data.frame()
  for(i in 1:length(recovered)){
    recovered_data <- rbind(recovered_data, data.frame(recovered[[i]]))

  }

  recovered_data <- recovered_data %>%
    mutate(date_recovered=as.Date(date_recovered, format = "%d-%m-%Y"))%>%
    mutate(province = replace(province, province %in% c("BC"), "British Columbia"),
           province = replace(province, province %in% c("NL"), "Newfoundland and Labrador"),
           province = replace(province, province %in% c("NWT"), "Northwest Territories"),
           province = replace(province, province %in% c("PEI"), "Prince Edward Island")) %>%
    mutate(year = format(date_recovered, format = "%Y"))

  recovered_data <- recovered_data[, c(2, 3, 1, 4,5)]

  if(ryear %!in% unique(recovered_data$year)){
    stop("There is no data for this year!")
  }
  
  if(tolower(provinceName) == 'canada'){
    recovered_data <- recovered_data %>%
      filter(year == ryear)
    return(recovered_data)
  } else {
    recovered_data <- recovered_data %>%
      filter(tolower(province) == tolower(provinceName), year == ryear)
    return(recovered_data)
  }
}
yearly_recovered(provinceName = "canada", ryear = "2022")
```










